# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build with Maven
        run: mvn clean package

      - name: create docker image
        run: docker-compose up -d

      - uses: actions/checkout@v1
      - name: docker login and push
        run: | 
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD --password-stdin
      - name: push
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/spring_boot_api_mysql
          docker push ${{secrets.DOCKERHUB_USERNAME}}/spring_boot_api_1


#        run: mvn -B package --file pom.xml
#      - uses: mr-smithers-excellent/docker-build-push@v5
#        name: Build and push docker image
#        with:
#          image: vinsstha/springboot-library-management-api
#          tags: v1
#          registry: docker.io
#          dockerfile: "docker-compose.yaml"
#          username: ${{secrets.DOCKERHUB_USERNAME}}
#          password: ${{secrets.DOCKERHUB_PASSWORD}}

